services:
  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - 3000:3000
    depends_on:
      - backend
    command: sh -c "yarn && yarn dev"

  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    ports:
      - 8000:8000
    depends_on:
      - redis
    command: sh -c "cd messaging && python manage.py migrate && python manage.py runserver 0.0.0.0:8000" 

  redis:
    image: redis
    container_name: redis-server
